[IDS]: Modified typo tokens and small type refacts
i-Cell-Mobilsoft-Open-Source/ids-vue pull request #67
Opened 2024-06-12 13:09 UTC by Vandi96

2024-06-12 13:12 UTC, svensson1982 approved these changes
👍

2024-06-12 16:30 UTC, difecto requested changes

2024-06-12 16:30 UTC, difecto commented on src/styles/tokens.scss
> +  --ids-base-percentage-025: 0.25px;
percentage px problem. Will be fixed in ids-tokens.

2024-06-14 12:37 UTC, difecto approved these changes

2024-06-17 07:43 UTC, merged